export const SALES_DATA_SQL = `
SELECT 
  OU_NAME,
  TO_CHAR(TRX_DATE, 'YYYY') AS YR,
  ROUND(SUM(QUANTITY_INVOICED * UNIT_SELLING_PRICE * Ou_Currency_Conv_Rate) / 10000000, 2) AS SALE_VAL
FROM JAN_ALL_OU_ORD_SALES_V 
WHERE 1 = 1
  AND ORD_EMPT_STATUS = 'N'
  AND SOURCE_NAME = 'SALES'
  AND TRX_DATE >= TO_DATE(:fromDate1, 'YYYY-MM-DD')
  AND (:region1 IS NULL OR UPPER(OU_NAME) = UPPER(:region2))
GROUP BY 
  OU_NAME, 
  TO_CHAR(TRX_DATE, 'YYYY')
ORDER BY 
  YR DESC, 
  OU_NAME ASC
`;

export const SALES_SUMMARY_SQL = `
SELECT 
  OU_NAME,
  TO_CHAR(ORDERED_DATE, 'YYYY') AS YR,
  ROUND(SUM(PEND_QUANTITY * UNIT_SELLING_PRICE * Ou_Currency_Conv_Rate) / 10000000, 2) AS PEND_ORD_VAL
FROM JAN_ALL_OU_ORD_SALES_V 
WHERE 1 = 1
  AND ORD_EMPT_STATUS = 'N'
  AND SOURCE_NAME = 'ORDER'
  AND ORDERED_DATE >= TO_DATE(:fromDate2, 'YYYY-MM-DD')
  AND (:region3 IS NULL OR UPPER(OU_NAME) = UPPER(:region4))
GROUP BY 
  OU_NAME, 
  TO_CHAR(ORDERED_DATE, 'YYYY')
ORDER BY 
  YR DESC, 
  OU_NAME ASC
`;
