SELECT 
    TO_CHAR(ORDERED_DATE, 'YYYY-MM') YRMN, 
    TO_CHAR(ORDERED_DATE, 'MON-YY') MNYR,
    ROUND(SUM(ORDERED_QUANTITY * UNIT_SELLING_PRICE * OU_CURRENCY_CONV_RATE) / 1000000, 2) ORDER_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_ORD_SALES_V 
WHERE 
    SOURCE_NAME = 'ORDER' 
    AND ORDERED_DATE >= TO_DATE('2025-04-01', 'YYYY-MM-DD')
    AND STK_TFR_FLG = 'N' 
    AND ORD_EMPT_STATUS = 'N'
GROUP BY 
    TO_CHAR(ORDERED_DATE, 'YYYY-MM'), 
    TO_CHAR(ORDERED_DATE, 'MON-YY'), 
    ORG_ID, 
    OU_NAME
ORDER BY 
    YRMN ASC;
    
    
SELECT 
    TO_CHAR(TRX_DATE, 'YYYYMM') YRMN, 
    TO_CHAR(TRX_DATE, 'MON-YY') MNYR,
    ROUND(SUM(QUANTITY_INVOICED * UNIT_SELLING_PRICE * OU_CURRENCY_CONV_RATE) / 1000000, 2) SALES_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_ORD_SALES_V
WHERE 
    SOURCE_NAME = 'SALES' 
    AND TRX_DATE >= TO_DATE('2025-04-01', 'YYYY-MM-DD')
    AND STK_TFR_FLG = 'N' 
    AND ORD_EMPT_STATUS = 'N' 
GROUP BY 
    TO_CHAR(TRX_DATE, 'YYYYMM'), 
    TO_CHAR(TRX_DATE, 'MON-YY'), 
    ORG_ID, 
    OU_NAME
ORDER BY 
    YRMN ASC;


CREATE TABLE JAN_ALL_OU_ORD (
    YRMN        CHAR(7) NOT NULL,
    MNYR        CHAR(6) NOT NULL,
    ORDER_VALUE DECIMAL(18, 2) NOT NULL,
    OU_NAME     VARCHAR(100) NOT NULL,
    ORG_ID      INT NOT NULL,
);

CREATE NONCLUSTERED INDEX IX_JAN_ALL_OU_ORD_DASHBOARD
ON JAN_ALL_OU_ORD (ORG_ID, YRMN)
INCLUDE (MNYR, ORDER_VALUE, OU_NAME);

CREATE TABLE JAN_ALL_OU_SALES (
    YRMN        CHAR(6) NOT NULL,
    MNYR        CHAR(6) NOT NULL,
    SALES_VALUE DECIMAL(18, 2) NOT NULL,
    OU_NAME     VARCHAR(100) NOT NULL,
    ORG_ID      INT NOT NULL
);

CREATE NONCLUSTERED INDEX IX_JAN_ALL_OU_SALES_DASHBOARD
ON JAN_ALL_OU_SALES (ORG_ID, YRMN)
INCLUDE (MNYR, SALES_VALUE, OU_NAME);


SELECT 
    YRMN, 
    MNYR, 
    ORDER_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_ORD
WHERE 
    -- FOR "ALL UNITS", REMOVE THIS WHERE CLAUSE ENTIRELY
    -- FOR A SPECIFIC UNIT, PASS THE CLICKED ID (e.g., 103, 684)
    ORG_ID = 103 
ORDER BY 
    YRMN ASC;


SELECT 
    YRMN, 
    MNYR, 
    SALES_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_SALES
WHERE 
    -- FOR "ALL UNITS", REMOVE THIS WHERE CLAUSE ENTIRELY
    -- FOR A SPECIFIC UNIT, PASS THE CLICKED ID (e.g., 103, 684)
    ORG_ID = 103 
ORDER BY 
    YRMN ASC;


const string sqlQuerySales = @"
SELECT 
    YRMN, 
    MNYR, 
    SALES_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_SALES
WHERE 
    (@OrgId IS NULL OR ORG_ID = @OrgId)
ORDER BY 
    YRMN ASC;";


const string sqlQueryOrders = @"
SELECT 
    YRMN, 
    MNYR, 
    ORDER_VALUE, 
    OU_NAME, 
    ORG_ID 
FROM 
    JAN_ALL_OU_ORD
WHERE 
    (@OrgId IS NULL OR ORG_ID = @OrgId)
ORDER BY 
    YRMN ASC;";
